-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 13:19:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion_vuelos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_vuelos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_vuelos` DEFAULT CHARACTER SET utf8mb4 ;
USE `gestion_vuelos` ;

-- -----------------------------------------------------
-- Table `gestion_vuelos`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`nacionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`nacionalidades` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nacionalidad` VARCHAR(100) NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`paises` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(100) NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`ciudades` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(100) NOT NULL,
  `pais` BIGINT(20) UNSIGNED NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudades_paises1_idx` (`pais` ASC) VISIBLE,
  CONSTRAINT `fk_ciudades_paises1`
    FOREIGN KEY (`pais`)
    REFERENCES `gestion_vuelos`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`categorias` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(100) NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`aerolineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`aerolineas` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `aerolinea` VARCHAR(100) NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`usuarios` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_documento` BIGINT(20) UNSIGNED NOT NULL,
  `identificacion` VARCHAR(75) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `ciudad` BIGINT(20) UNSIGNED NOT NULL,
  `pais` BIGINT(20) UNSIGNED NOT NULL,
  `genero` ENUM("M", "F", "OTROS") NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `nacionalidad` BIGINT(20) UNSIGNED NOT NULL,
  `tipo_de_sangre` VARCHAR(3) NULL,
  `rol` BIGINT(20) UNSIGNED NOT NULL,
  `categoria` BIGINT(20) UNSIGNED NULL,
  `aerolinea` BIGINT(20) UNSIGNED NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_roles_idx` (`rol` ASC) VISIBLE,
  INDEX `fk_usuarios_nacionalidades1_idx` (`nacionalidad` ASC) VISIBLE,
  INDEX `fk_usuarios_ciudades1_idx` (`ciudad` ASC) VISIBLE,
  INDEX `fk_usuarios_categorias1_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_usuarios_paises1_idx` (`pais` ASC) VISIBLE,
  INDEX `fk_usuarios_aerolineas1_idx` (`aerolinea` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`rol`)
    REFERENCES `gestion_vuelos`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_nacionalidades1`
    FOREIGN KEY (`nacionalidad`)
    REFERENCES `gestion_vuelos`.`nacionalidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_ciudades1`
    FOREIGN KEY (`ciudad`)
    REFERENCES `gestion_vuelos`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `gestion_vuelos`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_paises1`
    FOREIGN KEY (`pais`)
    REFERENCES `gestion_vuelos`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_aerolineas1`
    FOREIGN KEY (`aerolinea`)
    REFERENCES `gestion_vuelos`.`aerolineas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`aviones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`aviones` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `avion` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `capacidad` INT(20) NOT NULL,
  `matricula` VARCHAR(100) NOT NULL,
  `numero_de_silla` VARCHAR(100) NOT NULL,
  `aerolineas_id` BIGINT(20) UNSIGNED NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_aviones_aerolineas1_idx` (`aerolineas_id` ASC) VISIBLE,
  CONSTRAINT `fk_aviones_aerolineas1`
    FOREIGN KEY (`aerolineas_id`)
    REFERENCES `gestion_vuelos`.`aerolineas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`estados_de_vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`estados_de_vuelos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado_de_vuelo` VARCHAR(100) NOT NULL,
  `detalle` VARCHAR(100) NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`vuelos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(8) NOT NULL,
  `origen` BIGINT(20) UNSIGNED NOT NULL,
  `destino` BIGINT(20) UNSIGNED NOT NULL,
  `salida` DATETIME NOT NULL,
  `llegada` DATETIME NOT NULL,
  `estado_vuelio` BIGINT(20) UNSIGNED NOT NULL,
  `avion` BIGINT(20) UNSIGNED NOT NULL,
  `aerolinea` BIGINT(20) UNSIGNED NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_vuelos_aviones1_idx` (`avion` ASC) VISIBLE,
  INDEX `fk_vuelos_estados_de_vuelos1_idx` (`estado_vuelio` ASC) VISIBLE,
  INDEX `fk_vuelos_aerolineas1_idx` (`aerolinea` ASC) VISIBLE,
  INDEX `fk_vuelos_ciudades1_idx` (`origen` ASC) VISIBLE,
  INDEX `fk_vuelos_ciudades2_idx` (`destino` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_aviones1`
    FOREIGN KEY (`avion`)
    REFERENCES `gestion_vuelos`.`aviones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_estados_de_vuelos1`
    FOREIGN KEY (`estado_vuelio`)
    REFERENCES `gestion_vuelos`.`estados_de_vuelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_aerolineas1`
    FOREIGN KEY (`aerolinea`)
    REFERENCES `gestion_vuelos`.`aerolineas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_ciudades1`
    FOREIGN KEY (`origen`)
    REFERENCES `gestion_vuelos`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_ciudades2`
    FOREIGN KEY (`destino`)
    REFERENCES `gestion_vuelos`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`reservas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reserva` VARCHAR(100) NOT NULL,
  `fecha_de_reserva` DATE NOT NULL,
  `fecha_de_cancelancion` DATE NOT NULL,
  `motivo_de_cancelacion` VARCHAR(100) NOT NULL,
  `vuelo` BIGINT(20) UNSIGNED NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_reservas_vuelos1_idx` (`vuelo` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_vuelos1`
    FOREIGN KEY (`vuelo`)
    REFERENCES `gestion_vuelos`.`vuelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`pqrs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(500) NULL,
  `pqr` VARCHAR(100) NOT NULL,
  `usuario` BIGINT(20) UNSIGNED NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_pqrs_usuarios1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_pqrs_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `gestion_vuelos`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`servicio_al_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`servicio_al_usuario` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `servicio_al_usuario` VARCHAR(45) NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`usuarios_has_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`usuarios_has_reservas` (
  `usuarios_id` BIGINT(20) UNSIGNED NOT NULL,
  `reservas_id` BIGINT(20) UNSIGNED NOT NULL,
  `creado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`usuarios_id`, `reservas_id`),
  INDEX `fk_usuarios_has_reservas_reservas1_idx` (`reservas_id` ASC) VISIBLE,
  INDEX `fk_usuarios_has_reservas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_reservas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `gestion_vuelos`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_reservas_reservas1`
    FOREIGN KEY (`reservas_id`)
    REFERENCES `gestion_vuelos`.`reservas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_vuelos`.`reservas_has_aerolineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_vuelos`.`reservas_has_aerolineas` (
  `reservas_id` BIGINT(20) UNSIGNED NOT NULL,
  `aerolineas_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`reservas_id`, `aerolineas_id`),
  INDEX `fk_reservas_has_aerolineas_aerolineas1_idx` (`aerolineas_id` ASC) VISIBLE,
  INDEX `fk_reservas_has_aerolineas_reservas1_idx` (`reservas_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_has_aerolineas_reservas1`
    FOREIGN KEY (`reservas_id`)
    REFERENCES `gestion_vuelos`.`reservas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_has_aerolineas_aerolineas1`
    FOREIGN KEY (`aerolineas_id`)
    REFERENCES `gestion_vuelos`.`aerolineas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
